env:
  - NODE_VERSION=0.8
  - NODE_VERSION=0.10
  - NODE_VERSION=0.11

os:
  - linux
  - osx
  
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./travis-linux.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./travis-osx.sh; fi
  - . ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - npm config set spin false
  - node --version
  - npm --version
  
install:
  - npm install
  
script:
  - npm test
