language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
  
os:
  - linux
  
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./travis-linux.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./travis-osx.sh; fi
